name: vision
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cpython=3.11.14=py311hd8ed1ab_3
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.1=hd92462c_3
  - filelock=3.20.3=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_2
  - icu=78.2=h33c6efd_0
  - jinja2=3.1.6=pyhcf101f3_1
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.2=hb03c661_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=13.1.115=he32a221_0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py311h3778330_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.1=py311h2e04523_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=26.0=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=hd63d673_2_cpython
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=py3.11_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h3778330_0
  - readline=8.3=h853b02a_0
  - setuptools=80.10.1=pyh332efcf_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hb700be7_5
  - tk=8.6.13=noxft_h366c992_103
  - torchtriton=3.1.0=py311
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - uv=0.9.26=h76e24b7_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/lpotvin/miniforge3/envs/vision
